import isArguments from './isArguments'
import isArrayLike from './isArrayLike'
import isBoolean from './isBoolean'
import isElement from './isElement'
import isFunction from './isFunction'
import isLength from './isLength'
// import isMap from '../../ignore/isMap'
import isNull from './isNull'
import isDate from './isDate'
import isNumber from './isNumber'
import isObject from './isObject'
import isObjectLike from './isObjectLike'
import isPlainObject from './isPlainObject'
import isRegExp from './isRegExp'
import isSet from './isSet'
import isString from './isString'
import isSymbol from './isSymbol'

export default { isArguments, isArrayLike, isBoolean, isElement, isFunction, isDate, isLength, isNull, isNumber, isObject, isObjectLike, isPlainObject, isRegExp, isSet, isString, isSymbol }